#!/usr/bin/env python3
"""
AUDITORÍA COMPLETA: ClinicForge vs CRM Ventas - Meta Ads Implementation
Compara todos los componentes de Meta Ads entre ambos proyectos.
"""

import os
import sys
import json
from pathlib import Path
import difflib

def print_header(text):
    print("\n" + "=" * 80)
    print(f"🔍 {text}")
    print("=" * 80)

def print_section(text):
    print(f"\n📁 {text}")
    print("-" * 60)

def print_success(msg):
    print(f"✅ {msg}")

def print_warning(msg):
    print(f"⚠️  {msg}")

def print_error(msg):
    print(f"❌ {msg}")

def print_info(msg):
    print(f"ℹ️  {msg}")

def compare_files(file1, file2, description):
    """Compare two files and show differences"""
    try:
        with open(file1, 'r', encoding='utf-8') as f1:
            content1 = f1.read()
        with open(file2, 'r', encoding='utf-8') as f2:
            content2 = f2.read()
        
        if content1 == content2:
            print_success(f"{description}: IDÉNTICOS")
            return True, 100
        else:
            # Calculate similarity
            similarity = difflib.SequenceMatcher(None, content1, content2).ratio() * 100
            
            # Count lines
            lines1 = content1.count('\n')
            lines2 = content2.count('\n')
            
            if similarity > 90:
                print_success(f"{description}: SIMILAR ({similarity:.1f}%) - Líneas: {lines1}→{lines2}")
            elif similarity > 70:
                print_warning(f"{description}: MODERADAMENTE SIMILAR ({similarity:.1f}%) - Líneas: {lines1}→{lines2}")
            else:
                print_error(f"{description}: DIFERENTES ({similarity:.1f}%) - Líneas: {lines1}→{lines2}")
            
            return False, similarity
    except Exception as e:
        print_error(f"{description}: Error comparando - {e}")
        return False, 0

def check_file_exists(path, description):
    """Check if file exists"""
    if Path(path).exists():
        return True
    else:
        print_error(f"{description}: NO ENCONTRADO - {path}")
        return False

def analyze_terminology_changes(content1, content2):
    """Analyze terminology changes between ClinicForge and CRM Ventas"""
    changes = {
        # ClinicForge → CRM Ventas
        "patient": "lead",
        "patients": "leads",
        "appointment": "opportunity",
        "appointments": "opportunities",
        "clinic": "account",
        "clinics": "accounts",
        "dental": "sales",
        "medical": "business",
        "treatment": "service",
        "doctor": "manager",
        "nurse": "assistant",
        "health": "business",
        "medical_record": "client_record",
        "prescription": "proposal",
        "diagnosis": "analysis",
        "symptom": "requirement",
        "procedure": "process",
        "insurance": "payment_plan",
        "co-pay": "down_payment",
        "follow-up": "follow_up",
        "check-up": "review",
        "consultation": "meeting",
        "emergency": "urgent",
        "ward": "department",
        "hospital": "company",
        "pharmacy": "warehouse",
        "lab": "analysis_center",
        "x-ray": "scan",
        "test": "assessment",
        "result": "outcome",
        "vital": "key_metric",
        "sign": "indicator",
        "symptom": "signal",
        "condition": "situation",
        "disease": "problem",
        "therapy": "solution",
        "recovery": "resolution",
        "discharge": "completion",
        "admission": "onboarding",
        "referral": "introduction",
        "specialist": "expert",
        "general practitioner": "general_manager",
        "surgeon": "specialist",
        "anesthesiologist": "coordinator",
        "radiologist": "analyst",
        "pathologist": "researcher",
        "physician": "professional",
        "dentist": "sales_executive",
        "orthodontist": "senior_executive",
        "periodontist": "account_manager",
        "endodontist": "specialist_manager",
        "prosthodontist": "solution_manager",
        "hygienist": "assistant_manager",
        "assistant": "junior_executive",
        "receptionist": "reception",
        "administrator": "administrator",
        "billing": "billing",
        "coding": "coding",
        "claim": "invoice",
        "reimbursement": "payment",
        "deductible": "minimum_payment",
        "coverage": "coverage",
        "policy": "policy",
        "provider": "provider",
        "network": "network",
        "formulary": "catalog",
        "generic": "standard",
        "brand": "premium",
        "dosage": "quantity",
        "frequency": "frequency",
        "duration": "duration",
        "route": "channel",
        "indication": "purpose",
        "contraindication": "restriction",
        "side effect": "side_effect",
        "adverse event": "issue",
        "allergy": "sensitivity",
        "intolerance": "incompatibility",
        "interaction": "interaction",
        "monitoring": "monitoring",
        "compliance": "compliance",
        "adherence": "adherence",
        "outcome": "result",
        "quality of life": "satisfaction",
        "functional status": "performance",
        "disability": "limitation",
        "handicap": "challenge",
        "impairment": "deficiency",
        "limitation": "constraint",
        "restriction": "restriction",
        "ability": "capability",
        "capacity": "capacity",
        "skill": "skill",
        "competence": "competence",
        "proficiency": "proficiency",
        "expertise": "expertise",
        "knowledge": "knowledge",
        "understanding": "understanding",
        "awareness": "awareness",
        "consciousness": "consciousness",
        "orientation": "orientation",
        "memory": "memory",
        "attention": "attention",
        "concentration": "concentration",
        "cognition": "cognition",
        "perception": "perception",
        "thought": "thought",
        "emotion": "emotion",
        "mood": "mood",
        "affect": "affect",
        "behavior": "behavior",
        "conduct": "conduct",
        "action": "action",
        "reaction": "reaction",
        "response": "response",
        "adaptation": "adaptation",
        "adjustment": "adjustment",
        "coping": "coping",
        "stress": "stress",
        "anxiety": "anxiety",
        "depression": "depression",
        "distress": "distress",
        "suffering": "suffering",
        "pain": "pain",
        "discomfort": "discomfort",
        "pleasure": "pleasure",
        "satisfaction": "satisfaction",
        "happiness": "happiness",
        "well-being": "well_being",
        "health status": "business_status",
        "medical history": "client_history",
        "family history": "company_history",
        "social history": "market_history",
        "occupational history": "professional_history",
        "environmental history": "environmental_history",
        "developmental history": "development_history",
        "educational history": "education_history",
        "cultural history": "cultural_history",
        "spiritual history": "values_history",
        "sexual history": "relationship_history",
        "substance use": "resource_use",
        "tobacco": "tobacco",
        "alcohol": "alcohol",
        "drug": "substance",
        "medication": "resource",
        "supplement": "addition",
        "vitamin": "enhancement",
        "herb": "natural_resource",
        "alternative therapy": "alternative_solution",
        "complementary medicine": "complementary_resource",
        "traditional medicine": "traditional_resource",
        "folk medicine": "local_resource",
        "spiritual healing": "value_based_solution",
        "energy healing": "energy_based_solution",
        "mind-body therapy": "mind_body_solution",
        "manipulative therapy": "manual_solution",
        "movement therapy": "movement_solution",
        "expressive therapy": "expressive_solution",
        "creative therapy": "creative_solution",
        "recreational therapy": "recreational_solution",
        "vocational therapy": "vocational_solution",
        "educational therapy": "educational_solution",
        "cognitive therapy": "cognitive_solution",
        "behavioral therapy": "behavioral_solution",
        "psychodynamic therapy": "psychodynamic_solution",
        "humanistic therapy": "humanistic_solution",
        "existential therapy": "existential_solution",
        "transpersonal therapy": "transpersonal_solution",
        "integrative therapy": "integrative_solution",
        "holistic therapy": "holistic_solution",
        "biopsychosocial model": "biopsychosocial_model",
        "medical model": "business_model",
        "social model": "social_model",
        "cultural model": "cultural_model",
        "spiritual model": "values_model",
        "ecological model": "ecological_model",
        "systems theory": "systems_theory",
        "complexity theory": "complexity_theory",
        "chaos theory": "chaos_theory",
        "network theory": "network_theory",
        "game theory": "game_theory",
        "decision theory": "decision_theory",
        "information theory": "information_theory",
        "communication theory": "communication_theory",
        "learning theory": "learning_theory",
        "memory theory": "memory_theory",
        "attention theory": "attention_theory",
        "perception theory": "perception_theory",
        "cognition theory": "cognition_theory",
        "emotion theory": "emotion_theory",
        "motivation theory": "motivation_theory",
        "personality theory": "personality_theory",
        "social theory": "social_theory",
        "cultural theory": "cultural_theory",
        "political theory": "political_theory",
        "economic theory": "economic_theory",
        "legal theory": "legal_theory",
        "ethical theory": "ethical_theory",
        "aesthetic theory": "aesthetic_theory",
        "religious theory": "religious_theory",
        "philosophical theory": "philosophical_theory",
        "scientific theory": "scientific_theory",
        "mathematical theory": "mathematical_theory",
        "physical theory": "physical_theory",
        "chemical theory": "chemical_theory",
        "biological theory": "biological_theory",
        "psychological theory": "psychological_theory",
        "sociological theory": "sociological_theory",
        "anthropological theory": "anthropological_theory",
        "historical theory": "historical_theory",
        "geographical theory": "geographical_theory",
        "linguistic theory": "linguistic_theory",
        "literary theory": "literary_theory",
        "art theory": "art_theory",
        "music theory": "music_theory",
        "dance theory": "dance_theory",
        "theater theory": "theater_theory",
        "film theory": "film_theory",
        "media theory": "media_theory",
        "technology theory": "technology_theory",
        "engineering theory": "engineering_theory",
        "computer theory": "computer_theory",
        "information theory": "information_theory",
        "systems theory": "systems_theory",
        "control theory": "control_theory",
        "communication theory": "communication_theory",
        "cybernetics": "cybernetics",
        "robotics": "robotics",
        "artificial intelligence": "artificial_intelligence",
        "machine learning": "machine_learning",
        "deep learning": "deep_learning",
        "neural networks": "neural_networks",
        "natural language processing": "natural_language_processing",
        "computer vision": "computer_vision",
        "speech recognition": "speech_recognition",
        "image recognition": "image_recognition",
        "pattern recognition": "pattern_recognition",
        "data mining": "data_mining",
        "big data": "big_data",
        "data science": "data_science",
        "statistics": "statistics",
        "probability": "probability",
        "mathematics": "mathematics",
        "logic": "logic",
        "algebra": "algebra",
        "geometry": "geometry",
        "calculus": "calculus",
        "analysis": "analysis",
        "topology": "topology",
        "number theory": "number_theory",
        "set theory": "set_theory",
        "category theory": "category_theory",
        "type theory": "type_theory",
        "proof theory": "proof_theory",
        "model theory": "model_theory",
        "recursion theory": "recursion_theory",
        "complexity theory": "complexity_theory",
        "algorithm theory": "algorithm_theory",
        "computation theory": "computation_theory",
        "automata theory": "automata_theory",
        "formal language theory": "formal_language_theory",
        "grammar theory": "grammar_theory",
        "parsing theory": "parsing_theory",
        "compiler theory": "compiler_theory",
        "operating system theory": "operating_system_theory",
        "database theory": "database_theory",
        "network theory": "network_theory",
        "security theory": "security_theory",
        "cryptography": "cryptography",
        "coding theory": "coding_theory",
        "information theory": "information_theory",
        "signal theory": "signal_theory",
        "system theory": "system_theory",
        "control theory": "control_theory",
        "estimation theory": "estimation_theory",
        "detection theory": "detection_theory",
        "decision theory": "decision_theory",
        "game theory": "game_theory",
        "utility theory": "utility_theory",
        "risk theory": "risk_theory",
        "portfolio theory": "portfolio_theory",
        "market theory": "market_theory",
        "price theory": "price_theory",
        "competition theory": "competition_theory",
        "monopoly theory": "monopoly_theory",
        "oligopoly theory": "oligopoly_theory",
        "duopoly theory": "duopoly_theory",
        "cartel theory": "cartel_theory",
        "collusion theory": "collusion_theory",
        "predation theory": "predation_theory",
        "entry theory": "entry_theory",
        "exit theory": "exit_theory",
        "innovation theory": "innovation_theory",
        "growth theory": "growth_theory",
        "development theory": "development_theory",
        "cycle theory": "cycle_theory",
        "crisis theory": "crisis_theory",
        "recovery theory": "recovery_theory",
        "stability theory": "stability_theory",
        "instability theory": "instability_theory",
        "chaos theory": "chaos_theory",
        "complexity theory": "complexity_theory",
        "emergence theory": "emergence_theory",
        "self-organization theory": "self_organization_theory",
        "adaptation theory": "adaptation_theory",
        "evolution theory": "evolution_theory",
        "selection theory": "selection_theory",
        "mutation theory": "mutation_theory",
        "recombination theory": "recombination_theory",
        "drift theory": "drift_theory",
        "migration theory": "migration_theory",
        "speciation theory": "speciation_theory",
        "extinction theory": "extinction_theory",
        "biodiversity theory": "biodiversity_theory",
        "ecology theory": "ecology_theory",
        "ecosystem theory": "ecosystem_theory",
        "biome theory": "biome_theory",
        "biosphere theory": "biosphere_theory",
        "geosphere theory": "geosphere_theory",
        "hydrosphere theory": "hydrosphere_theory",
        "atmosphere theory": "atmosphere_theory",
        "climate theory": "climate_theory",
        "weather theory": "weather_theory",
        "ocean theory": "ocean_theory",
        "land theory": "land_theory",
        "soil theory": "soil_theory",
        "rock theory": "rock_theory",
        "mineral theory": "mineral_theory",
        "fossil theory": "fossil_theory",
        "paleontology theory": "paleontology_theory",
        "geology theory": "geology_theory",
        "geography theory": "geography_theory",
        "cartography theory": "cartography_theory",
        "topography theory": "topography_theory",
        "hydrology theory": "hydrology_theory",
        "meteorology theory": "meteorology_theory",
        "astronomy theory": "astronomy_theory",
        "astrophysics theory": "astrophysics_theory",
        "cosmology theory": "cosmology_theory",
        "particle